version: "3.9"

services:
  backend:
    container_name: procter-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PORT=8081
    networks:
      - procter-net

  frontend:
    container_name: procter-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - API_TARGET=http://backend:8081
    depends_on:
      - backend
    networks:
      - procter-net

networks:
  procter-net:
    driver: bridge

